### ISSUE TITLE
[BUG]: Extensions get loaded multiple times

### ISSUE THREAD

**Issue by KonnorRogers** [KonnorRogers/rhino-editor#215]

**Comment by KonnorRogers** [comment]
this one is really bizarre, but it was being caused by the `@tiptap/pm` module...

**Comment by KonnorRogers** [comment]
Should be fixed in 0.13.1!

**Comment by thil** [comment]
I feel like this is still a problem, getting a couple of calls on `addProseMirrorPlugins` as well as init state being called twice, or perhaps it is related to something different.
